# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-07 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNum', models.CharField(max_length=20)),
                ('streetNum', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('squareFoot', models.CharField(max_length=10)),
                ('buildingConditionScore', models.CharField(max_length=5)),
                ('exteriorWalls', models.CharField(max_length=50)),
                ('fireplace', models.CharField(max_length=10)),
                ('garageCount', models.CharField(max_length=10)),
                ('numStories', models.CharField(max_length=10)),
                ('numBedrooms', models.CharField(max_length=10)),
                ('pool', models.CharField(max_length=10)),
                ('propertyType', models.CharField(max_length=50)),
                ('roofCover', models.CharField(max_length=30)),
                ('propertyAcreage', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=50)),
                ('numBaths', models.CharField(max_length=10)),
                ('yearBuilt', models.CharField(max_length=10)),
                ('apn', models.CharField(max_length=30)),
                ('assessmentYear', models.CharField(max_length=20)),
                ('taxYear', models.CharField(max_length=10)),
                ('totalAssessedValue', models.CharField(max_length=20)),
                ('taxAmount', models.CharField(max_length=20)),
                ('daysOld', models.CharField(max_length=10)),
                ('dateAdded', models.CharField(max_length=20)),
                ('geoLookup', models.CharField(max_length=30)),
                ('zipCode', models.CharField(max_length=20)),
            ],
        ),
    ]
