# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNum', models.CharField(max_length=20)),
                ('streetNum', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('equity', models.CharField(max_length=10)),
                ('zipCode', models.CharField(max_length=10)),
                ('currentlyOccupied', models.CharField(max_length=10)),
                ('lastSaleDate', models.CharField(max_length=40)),
                ('totalValue', models.CharField(max_length=20)),
                ('owners', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=40)),
                ('phoneType', models.CharField(max_length=40)),
                ('currentResidents', models.CharField(max_length=200)),
            ],
        ),
    ]
